# CMake generated Testfile for 
# Source directory: /home/randy/Workspace/REPOS/nikola
# Build directory: /home/randy/Workspace/REPOS/nikola/build_release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[MetabolicLock]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_metabolic_lock")
set_tests_properties([=[MetabolicLock]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;188;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[HilbertScanner]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_hilbert_scanner")
set_tests_properties([=[HilbertScanner]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;192;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Vector9D]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_vector9d")
set_tests_properties([=[Vector9D]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;197;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[PhysicsCore]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_physics_core")
set_tests_properties([=[PhysicsCore]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;202;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase2GeometryMemory]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase2_geometry_memory")
set_tests_properties([=[Phase2GeometryMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;207;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase3Cognitive]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase3_cognitive")
set_tests_properties([=[Phase3Cognitive]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;212;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase4Infrastructure]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase4_infrastructure")
set_tests_properties([=[Phase4Infrastructure]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;217;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase5Autonomous]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase5_autonomous")
set_tests_properties([=[Phase5Autonomous]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;222;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase6Multimodal]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase6_multimodal")
set_tests_properties([=[Phase6Multimodal]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;227;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase7Security]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase7_security")
set_tests_properties([=[Phase7Security]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;232;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase8Foundations]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase8_foundations")
set_tests_properties([=[Phase8Foundations]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;237;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase9Bootstrap]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase9_bootstrap")
set_tests_properties([=[Phase9Bootstrap]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;242;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase10Holographic]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase10_holographic")
set_tests_properties([=[Phase10Holographic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;247;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase11CognitiveGen]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase11_cognitive_gen")
set_tests_properties([=[Phase11CognitiveGen]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;252;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase12AcasBridge]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase12_acas_bridge")
set_tests_properties([=[Phase12AcasBridge]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;259;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase13TaskDispatcher]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase13_task_dispatcher")
set_tests_properties([=[Phase13TaskDispatcher]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;264;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase14AsyncCheckpoint]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase14_async_checkpoint")
set_tests_properties([=[Phase14AsyncCheckpoint]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;269;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase15HamiltonianValue]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase15_hamiltonian_value")
set_tests_properties([=[Phase15HamiltonianValue]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;274;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase16CoordSerializer]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase16_coord_serializer")
set_tests_properties([=[Phase16CoordSerializer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;279;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase17BootstrapManager]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase17_bootstrap_manager")
set_tests_properties([=[Phase17BootstrapManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;284;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase18ScopeProfiler]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase18_scope_profiler")
set_tests_properties([=[Phase18ScopeProfiler]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;289;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase19TelemetryDaemon]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase19_telemetry_daemon")
set_tests_properties([=[Phase19TelemetryDaemon]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;294;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase20DebugAdapter]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase20_debug_adapter")
set_tests_properties([=[Phase20DebugAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;299;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase21CognitivePipeline]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase21_cognitive_pipeline")
set_tests_properties([=[Phase21CognitivePipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;304;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase23DecisionLoop]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase23_decision_loop")
set_tests_properties([=[Phase23DecisionLoop]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;317;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase24ThoughtComposer]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase24_thought_composer")
set_tests_properties([=[Phase24ThoughtComposer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;322;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase25FieldPersistence]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase25_field_persistence")
set_tests_properties([=[Phase25FieldPersistence]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;327;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase26SeededExploration]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase26_seeded_exploration")
set_tests_properties([=[Phase26SeededExploration]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;332;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase27CrossInjection]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase27_cross_injection")
set_tests_properties([=[Phase27CrossInjection]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;337;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase28AnalyticDecode]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase28_analytic_decode")
set_tests_properties([=[Phase28AnalyticDecode]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;342;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase29NoveltyDecay]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase29_novelty_decay")
set_tests_properties([=[Phase29NoveltyDecay]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;347;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase30ZmqSpine]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase30_zmq_spine")
set_tests_properties([=[Phase30ZmqSpine]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;352;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase31LookupAgent]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase31_lookup_agent")
set_tests_properties([=[Phase31LookupAgent]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;357;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase32Escalation]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase32_escalation")
set_tests_properties([=[Phase32Escalation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;362;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase33MemoryPersistence]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase33_memory_persistence")
set_tests_properties([=[Phase33MemoryPersistence]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;367;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase34Recall]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase34_recall")
set_tests_properties([=[Phase34Recall]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;372;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase35RelevanceGate]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase35_relevance_gate")
set_tests_properties([=[Phase35RelevanceGate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;377;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase36GatedInjection]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase36_gated_injection")
set_tests_properties([=[Phase36GatedInjection]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;382;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase37NptStructure]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase37_npt_structure")
set_tests_properties([=[Phase37NptStructure]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;387;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase38WaveCorrelation]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase38_wave_correlation")
set_tests_properties([=[Phase38WaveCorrelation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;392;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase39CurvatureBias]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase39_curvature_bias")
set_tests_properties([=[Phase39CurvatureBias]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;397;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase40Heterodyne]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase40_heterodyne")
set_tests_properties([=[Phase40Heterodyne]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;402;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase41MultiheadMerge]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase41_multihead_merge")
set_tests_properties([=[Phase41MultiheadMerge]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;407;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase42NptReason]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase42_npt_reason")
set_tests_properties([=[Phase42NptReason]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;412;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
add_test([=[Phase43HebbianUpdate]=] "/home/randy/Workspace/REPOS/nikola/build_release/test_phase43_hebbian_update")
set_tests_properties([=[Phase43HebbianUpdate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;417;add_test;/home/randy/Workspace/REPOS/nikola/CMakeLists.txt;0;")
