// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irsp.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_irsp_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_irsp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_irsp_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_irsp_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_irsp_2eproto;
namespace nikola {
namespace social {
class EmpathySignal;
struct EmpathySignalDefaultTypeInternal;
extern EmpathySignalDefaultTypeInternal _EmpathySignal_default_instance_;
class PeerAnnouncement;
struct PeerAnnouncementDefaultTypeInternal;
extern PeerAnnouncementDefaultTypeInternal _PeerAnnouncement_default_instance_;
class ResonantPacket;
struct ResonantPacketDefaultTypeInternal;
extern ResonantPacketDefaultTypeInternal _ResonantPacket_default_instance_;
}  // namespace social
}  // namespace nikola
PROTOBUF_NAMESPACE_OPEN
template<> ::nikola::social::EmpathySignal* Arena::CreateMaybeMessage<::nikola::social::EmpathySignal>(Arena*);
template<> ::nikola::social::PeerAnnouncement* Arena::CreateMaybeMessage<::nikola::social::PeerAnnouncement>(Arena*);
template<> ::nikola::social::ResonantPacket* Arena::CreateMaybeMessage<::nikola::social::ResonantPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nikola {
namespace social {

// ===================================================================

class ResonantPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nikola.social.ResonantPacket) */ {
 public:
  inline ResonantPacket() : ResonantPacket(nullptr) {}
  ~ResonantPacket() override;
  explicit PROTOBUF_CONSTEXPR ResonantPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResonantPacket(const ResonantPacket& from);
  ResonantPacket(ResonantPacket&& from) noexcept
    : ResonantPacket() {
    *this = ::std::move(from);
  }

  inline ResonantPacket& operator=(const ResonantPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResonantPacket& operator=(ResonantPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResonantPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResonantPacket* internal_default_instance() {
    return reinterpret_cast<const ResonantPacket*>(
               &_ResonantPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResonantPacket& a, ResonantPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(ResonantPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResonantPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResonantPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResonantPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResonantPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResonantPacket& from) {
    ResonantPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResonantPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nikola.social.ResonantPacket";
  }
  protected:
  explicit ResonantPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEmitterRealFieldNumber = 4,
    kEmitterImagFieldNumber = 5,
    kIntentVectorFieldNumber = 6,
    kTextPayloadFieldNumber = 1,
    kSenderIdFieldNumber = 2,
    kSessionKeyFieldNumber = 3,
    kProtocolVersionFieldNumber = 8,
    kTimestampFieldNumber = 7,
  };
  // repeated double emitter_real = 4;
  int emitter_real_size() const;
  private:
  int _internal_emitter_real_size() const;
  public:
  void clear_emitter_real();
  private:
  double _internal_emitter_real(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_emitter_real() const;
  void _internal_add_emitter_real(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_emitter_real();
  public:
  double emitter_real(int index) const;
  void set_emitter_real(int index, double value);
  void add_emitter_real(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      emitter_real() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_emitter_real();

  // repeated double emitter_imag = 5;
  int emitter_imag_size() const;
  private:
  int _internal_emitter_imag_size() const;
  public:
  void clear_emitter_imag();
  private:
  double _internal_emitter_imag(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_emitter_imag() const;
  void _internal_add_emitter_imag(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_emitter_imag();
  public:
  double emitter_imag(int index) const;
  void set_emitter_imag(int index, double value);
  void add_emitter_imag(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      emitter_imag() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_emitter_imag();

  // repeated double intent_vector = 6;
  int intent_vector_size() const;
  private:
  int _internal_intent_vector_size() const;
  public:
  void clear_intent_vector();
  private:
  double _internal_intent_vector(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_intent_vector() const;
  void _internal_add_intent_vector(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_intent_vector();
  public:
  double intent_vector(int index) const;
  void set_intent_vector(int index, double value);
  void add_intent_vector(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      intent_vector() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_intent_vector();

  // string text_payload = 1;
  void clear_text_payload();
  const std::string& text_payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text_payload();
  PROTOBUF_NODISCARD std::string* release_text_payload();
  void set_allocated_text_payload(std::string* text_payload);
  private:
  const std::string& _internal_text_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text_payload(const std::string& value);
  std::string* _internal_mutable_text_payload();
  public:

  // string sender_id = 2;
  void clear_sender_id();
  const std::string& sender_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_id();
  PROTOBUF_NODISCARD std::string* release_sender_id();
  void set_allocated_sender_id(std::string* sender_id);
  private:
  const std::string& _internal_sender_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_id(const std::string& value);
  std::string* _internal_mutable_sender_id();
  public:

  // string session_key = 3;
  void clear_session_key();
  const std::string& session_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_key();
  PROTOBUF_NODISCARD std::string* release_session_key();
  void set_allocated_session_key(std::string* session_key);
  private:
  const std::string& _internal_session_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_key(const std::string& value);
  std::string* _internal_mutable_session_key();
  public:

  // string protocol_version = 8;
  void clear_protocol_version();
  const std::string& protocol_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_protocol_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_protocol_version();
  PROTOBUF_NODISCARD std::string* release_protocol_version();
  void set_allocated_protocol_version(std::string* protocol_version);
  private:
  const std::string& _internal_protocol_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_protocol_version(const std::string& value);
  std::string* _internal_mutable_protocol_version();
  public:

  // int64 timestamp = 7;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:nikola.social.ResonantPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > emitter_real_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > emitter_imag_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > intent_vector_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_payload_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protocol_version_;
    int64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_irsp_2eproto;
};
// -------------------------------------------------------------------

class EmpathySignal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nikola.social.EmpathySignal) */ {
 public:
  inline EmpathySignal() : EmpathySignal(nullptr) {}
  ~EmpathySignal() override;
  explicit PROTOBUF_CONSTEXPR EmpathySignal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EmpathySignal(const EmpathySignal& from);
  EmpathySignal(EmpathySignal&& from) noexcept
    : EmpathySignal() {
    *this = ::std::move(from);
  }

  inline EmpathySignal& operator=(const EmpathySignal& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmpathySignal& operator=(EmpathySignal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmpathySignal& default_instance() {
    return *internal_default_instance();
  }
  static inline const EmpathySignal* internal_default_instance() {
    return reinterpret_cast<const EmpathySignal*>(
               &_EmpathySignal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EmpathySignal& a, EmpathySignal& b) {
    a.Swap(&b);
  }
  inline void Swap(EmpathySignal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmpathySignal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmpathySignal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EmpathySignal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EmpathySignal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EmpathySignal& from) {
    EmpathySignal::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EmpathySignal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nikola.social.EmpathySignal";
  }
  protected:
  explicit EmpathySignal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionKeyFieldNumber = 1,
    kRespondingToSenderFieldNumber = 2,
    kFeedbackTextFieldNumber = 5,
    kResonanceScoreFieldNumber = 3,
    kDissonanceDetectedFieldNumber = 4,
  };
  // string session_key = 1;
  void clear_session_key();
  const std::string& session_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_key();
  PROTOBUF_NODISCARD std::string* release_session_key();
  void set_allocated_session_key(std::string* session_key);
  private:
  const std::string& _internal_session_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_key(const std::string& value);
  std::string* _internal_mutable_session_key();
  public:

  // string responding_to_sender = 2;
  void clear_responding_to_sender();
  const std::string& responding_to_sender() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_responding_to_sender(ArgT0&& arg0, ArgT... args);
  std::string* mutable_responding_to_sender();
  PROTOBUF_NODISCARD std::string* release_responding_to_sender();
  void set_allocated_responding_to_sender(std::string* responding_to_sender);
  private:
  const std::string& _internal_responding_to_sender() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_responding_to_sender(const std::string& value);
  std::string* _internal_mutable_responding_to_sender();
  public:

  // string feedback_text = 5;
  void clear_feedback_text();
  const std::string& feedback_text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_feedback_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_feedback_text();
  PROTOBUF_NODISCARD std::string* release_feedback_text();
  void set_allocated_feedback_text(std::string* feedback_text);
  private:
  const std::string& _internal_feedback_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_feedback_text(const std::string& value);
  std::string* _internal_mutable_feedback_text();
  public:

  // double resonance_score = 3;
  void clear_resonance_score();
  double resonance_score() const;
  void set_resonance_score(double value);
  private:
  double _internal_resonance_score() const;
  void _internal_set_resonance_score(double value);
  public:

  // double dissonance_detected = 4;
  void clear_dissonance_detected();
  double dissonance_detected() const;
  void set_dissonance_detected(double value);
  private:
  double _internal_dissonance_detected() const;
  void _internal_set_dissonance_detected(double value);
  public:

  // @@protoc_insertion_point(class_scope:nikola.social.EmpathySignal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr responding_to_sender_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr feedback_text_;
    double resonance_score_;
    double dissonance_detected_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_irsp_2eproto;
};
// -------------------------------------------------------------------

class PeerAnnouncement final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nikola.social.PeerAnnouncement) */ {
 public:
  inline PeerAnnouncement() : PeerAnnouncement(nullptr) {}
  ~PeerAnnouncement() override;
  explicit PROTOBUF_CONSTEXPR PeerAnnouncement(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PeerAnnouncement(const PeerAnnouncement& from);
  PeerAnnouncement(PeerAnnouncement&& from) noexcept
    : PeerAnnouncement() {
    *this = ::std::move(from);
  }

  inline PeerAnnouncement& operator=(const PeerAnnouncement& from) {
    CopyFrom(from);
    return *this;
  }
  inline PeerAnnouncement& operator=(PeerAnnouncement&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PeerAnnouncement& default_instance() {
    return *internal_default_instance();
  }
  static inline const PeerAnnouncement* internal_default_instance() {
    return reinterpret_cast<const PeerAnnouncement*>(
               &_PeerAnnouncement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PeerAnnouncement& a, PeerAnnouncement& b) {
    a.Swap(&b);
  }
  inline void Swap(PeerAnnouncement* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PeerAnnouncement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PeerAnnouncement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PeerAnnouncement>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PeerAnnouncement& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PeerAnnouncement& from) {
    PeerAnnouncement::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PeerAnnouncement* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nikola.social.PeerAnnouncement";
  }
  protected:
  explicit PeerAnnouncement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCapabilitiesFieldNumber = 3,
    kPeerIdFieldNumber = 1,
    kPublicKeyZ85FieldNumber = 2,
    kZmqEndpointFieldNumber = 4,
    kTimestampFieldNumber = 5,
  };
  // repeated string capabilities = 3;
  int capabilities_size() const;
  private:
  int _internal_capabilities_size() const;
  public:
  void clear_capabilities();
  const std::string& capabilities(int index) const;
  std::string* mutable_capabilities(int index);
  void set_capabilities(int index, const std::string& value);
  void set_capabilities(int index, std::string&& value);
  void set_capabilities(int index, const char* value);
  void set_capabilities(int index, const char* value, size_t size);
  std::string* add_capabilities();
  void add_capabilities(const std::string& value);
  void add_capabilities(std::string&& value);
  void add_capabilities(const char* value);
  void add_capabilities(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& capabilities() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_capabilities();
  private:
  const std::string& _internal_capabilities(int index) const;
  std::string* _internal_add_capabilities();
  public:

  // string peer_id = 1;
  void clear_peer_id();
  const std::string& peer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_peer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_peer_id();
  PROTOBUF_NODISCARD std::string* release_peer_id();
  void set_allocated_peer_id(std::string* peer_id);
  private:
  const std::string& _internal_peer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_peer_id(const std::string& value);
  std::string* _internal_mutable_peer_id();
  public:

  // string public_key_z85 = 2;
  void clear_public_key_z85();
  const std::string& public_key_z85() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_public_key_z85(ArgT0&& arg0, ArgT... args);
  std::string* mutable_public_key_z85();
  PROTOBUF_NODISCARD std::string* release_public_key_z85();
  void set_allocated_public_key_z85(std::string* public_key_z85);
  private:
  const std::string& _internal_public_key_z85() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_public_key_z85(const std::string& value);
  std::string* _internal_mutable_public_key_z85();
  public:

  // string zmq_endpoint = 4;
  void clear_zmq_endpoint();
  const std::string& zmq_endpoint() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_zmq_endpoint(ArgT0&& arg0, ArgT... args);
  std::string* mutable_zmq_endpoint();
  PROTOBUF_NODISCARD std::string* release_zmq_endpoint();
  void set_allocated_zmq_endpoint(std::string* zmq_endpoint);
  private:
  const std::string& _internal_zmq_endpoint() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_zmq_endpoint(const std::string& value);
  std::string* _internal_mutable_zmq_endpoint();
  public:

  // int64 timestamp = 5;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:nikola.social.PeerAnnouncement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> capabilities_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr peer_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr public_key_z85_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zmq_endpoint_;
    int64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_irsp_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResonantPacket

// string text_payload = 1;
inline void ResonantPacket::clear_text_payload() {
  _impl_.text_payload_.ClearToEmpty();
}
inline const std::string& ResonantPacket::text_payload() const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.text_payload)
  return _internal_text_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ResonantPacket::set_text_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_payload_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.text_payload)
}
inline std::string* ResonantPacket::mutable_text_payload() {
  std::string* _s = _internal_mutable_text_payload();
  // @@protoc_insertion_point(field_mutable:nikola.social.ResonantPacket.text_payload)
  return _s;
}
inline const std::string& ResonantPacket::_internal_text_payload() const {
  return _impl_.text_payload_.Get();
}
inline void ResonantPacket::_internal_set_text_payload(const std::string& value) {
  
  _impl_.text_payload_.Set(value, GetArenaForAllocation());
}
inline std::string* ResonantPacket::_internal_mutable_text_payload() {
  
  return _impl_.text_payload_.Mutable(GetArenaForAllocation());
}
inline std::string* ResonantPacket::release_text_payload() {
  // @@protoc_insertion_point(field_release:nikola.social.ResonantPacket.text_payload)
  return _impl_.text_payload_.Release();
}
inline void ResonantPacket::set_allocated_text_payload(std::string* text_payload) {
  if (text_payload != nullptr) {
    
  } else {
    
  }
  _impl_.text_payload_.SetAllocated(text_payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_payload_.IsDefault()) {
    _impl_.text_payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.ResonantPacket.text_payload)
}

// string sender_id = 2;
inline void ResonantPacket::clear_sender_id() {
  _impl_.sender_id_.ClearToEmpty();
}
inline const std::string& ResonantPacket::sender_id() const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.sender_id)
  return _internal_sender_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ResonantPacket::set_sender_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.sender_id)
}
inline std::string* ResonantPacket::mutable_sender_id() {
  std::string* _s = _internal_mutable_sender_id();
  // @@protoc_insertion_point(field_mutable:nikola.social.ResonantPacket.sender_id)
  return _s;
}
inline const std::string& ResonantPacket::_internal_sender_id() const {
  return _impl_.sender_id_.Get();
}
inline void ResonantPacket::_internal_set_sender_id(const std::string& value) {
  
  _impl_.sender_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ResonantPacket::_internal_mutable_sender_id() {
  
  return _impl_.sender_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ResonantPacket::release_sender_id() {
  // @@protoc_insertion_point(field_release:nikola.social.ResonantPacket.sender_id)
  return _impl_.sender_id_.Release();
}
inline void ResonantPacket::set_allocated_sender_id(std::string* sender_id) {
  if (sender_id != nullptr) {
    
  } else {
    
  }
  _impl_.sender_id_.SetAllocated(sender_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_id_.IsDefault()) {
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.ResonantPacket.sender_id)
}

// string session_key = 3;
inline void ResonantPacket::clear_session_key() {
  _impl_.session_key_.ClearToEmpty();
}
inline const std::string& ResonantPacket::session_key() const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.session_key)
  return _internal_session_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ResonantPacket::set_session_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.session_key)
}
inline std::string* ResonantPacket::mutable_session_key() {
  std::string* _s = _internal_mutable_session_key();
  // @@protoc_insertion_point(field_mutable:nikola.social.ResonantPacket.session_key)
  return _s;
}
inline const std::string& ResonantPacket::_internal_session_key() const {
  return _impl_.session_key_.Get();
}
inline void ResonantPacket::_internal_set_session_key(const std::string& value) {
  
  _impl_.session_key_.Set(value, GetArenaForAllocation());
}
inline std::string* ResonantPacket::_internal_mutable_session_key() {
  
  return _impl_.session_key_.Mutable(GetArenaForAllocation());
}
inline std::string* ResonantPacket::release_session_key() {
  // @@protoc_insertion_point(field_release:nikola.social.ResonantPacket.session_key)
  return _impl_.session_key_.Release();
}
inline void ResonantPacket::set_allocated_session_key(std::string* session_key) {
  if (session_key != nullptr) {
    
  } else {
    
  }
  _impl_.session_key_.SetAllocated(session_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_key_.IsDefault()) {
    _impl_.session_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.ResonantPacket.session_key)
}

// repeated double emitter_real = 4;
inline int ResonantPacket::_internal_emitter_real_size() const {
  return _impl_.emitter_real_.size();
}
inline int ResonantPacket::emitter_real_size() const {
  return _internal_emitter_real_size();
}
inline void ResonantPacket::clear_emitter_real() {
  _impl_.emitter_real_.Clear();
}
inline double ResonantPacket::_internal_emitter_real(int index) const {
  return _impl_.emitter_real_.Get(index);
}
inline double ResonantPacket::emitter_real(int index) const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.emitter_real)
  return _internal_emitter_real(index);
}
inline void ResonantPacket::set_emitter_real(int index, double value) {
  _impl_.emitter_real_.Set(index, value);
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.emitter_real)
}
inline void ResonantPacket::_internal_add_emitter_real(double value) {
  _impl_.emitter_real_.Add(value);
}
inline void ResonantPacket::add_emitter_real(double value) {
  _internal_add_emitter_real(value);
  // @@protoc_insertion_point(field_add:nikola.social.ResonantPacket.emitter_real)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ResonantPacket::_internal_emitter_real() const {
  return _impl_.emitter_real_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ResonantPacket::emitter_real() const {
  // @@protoc_insertion_point(field_list:nikola.social.ResonantPacket.emitter_real)
  return _internal_emitter_real();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ResonantPacket::_internal_mutable_emitter_real() {
  return &_impl_.emitter_real_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ResonantPacket::mutable_emitter_real() {
  // @@protoc_insertion_point(field_mutable_list:nikola.social.ResonantPacket.emitter_real)
  return _internal_mutable_emitter_real();
}

// repeated double emitter_imag = 5;
inline int ResonantPacket::_internal_emitter_imag_size() const {
  return _impl_.emitter_imag_.size();
}
inline int ResonantPacket::emitter_imag_size() const {
  return _internal_emitter_imag_size();
}
inline void ResonantPacket::clear_emitter_imag() {
  _impl_.emitter_imag_.Clear();
}
inline double ResonantPacket::_internal_emitter_imag(int index) const {
  return _impl_.emitter_imag_.Get(index);
}
inline double ResonantPacket::emitter_imag(int index) const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.emitter_imag)
  return _internal_emitter_imag(index);
}
inline void ResonantPacket::set_emitter_imag(int index, double value) {
  _impl_.emitter_imag_.Set(index, value);
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.emitter_imag)
}
inline void ResonantPacket::_internal_add_emitter_imag(double value) {
  _impl_.emitter_imag_.Add(value);
}
inline void ResonantPacket::add_emitter_imag(double value) {
  _internal_add_emitter_imag(value);
  // @@protoc_insertion_point(field_add:nikola.social.ResonantPacket.emitter_imag)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ResonantPacket::_internal_emitter_imag() const {
  return _impl_.emitter_imag_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ResonantPacket::emitter_imag() const {
  // @@protoc_insertion_point(field_list:nikola.social.ResonantPacket.emitter_imag)
  return _internal_emitter_imag();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ResonantPacket::_internal_mutable_emitter_imag() {
  return &_impl_.emitter_imag_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ResonantPacket::mutable_emitter_imag() {
  // @@protoc_insertion_point(field_mutable_list:nikola.social.ResonantPacket.emitter_imag)
  return _internal_mutable_emitter_imag();
}

// repeated double intent_vector = 6;
inline int ResonantPacket::_internal_intent_vector_size() const {
  return _impl_.intent_vector_.size();
}
inline int ResonantPacket::intent_vector_size() const {
  return _internal_intent_vector_size();
}
inline void ResonantPacket::clear_intent_vector() {
  _impl_.intent_vector_.Clear();
}
inline double ResonantPacket::_internal_intent_vector(int index) const {
  return _impl_.intent_vector_.Get(index);
}
inline double ResonantPacket::intent_vector(int index) const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.intent_vector)
  return _internal_intent_vector(index);
}
inline void ResonantPacket::set_intent_vector(int index, double value) {
  _impl_.intent_vector_.Set(index, value);
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.intent_vector)
}
inline void ResonantPacket::_internal_add_intent_vector(double value) {
  _impl_.intent_vector_.Add(value);
}
inline void ResonantPacket::add_intent_vector(double value) {
  _internal_add_intent_vector(value);
  // @@protoc_insertion_point(field_add:nikola.social.ResonantPacket.intent_vector)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ResonantPacket::_internal_intent_vector() const {
  return _impl_.intent_vector_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ResonantPacket::intent_vector() const {
  // @@protoc_insertion_point(field_list:nikola.social.ResonantPacket.intent_vector)
  return _internal_intent_vector();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ResonantPacket::_internal_mutable_intent_vector() {
  return &_impl_.intent_vector_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ResonantPacket::mutable_intent_vector() {
  // @@protoc_insertion_point(field_mutable_list:nikola.social.ResonantPacket.intent_vector)
  return _internal_mutable_intent_vector();
}

// int64 timestamp = 7;
inline void ResonantPacket::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t ResonantPacket::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t ResonantPacket::timestamp() const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.timestamp)
  return _internal_timestamp();
}
inline void ResonantPacket::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void ResonantPacket::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.timestamp)
}

// string protocol_version = 8;
inline void ResonantPacket::clear_protocol_version() {
  _impl_.protocol_version_.ClearToEmpty();
}
inline const std::string& ResonantPacket::protocol_version() const {
  // @@protoc_insertion_point(field_get:nikola.social.ResonantPacket.protocol_version)
  return _internal_protocol_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ResonantPacket::set_protocol_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.protocol_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.ResonantPacket.protocol_version)
}
inline std::string* ResonantPacket::mutable_protocol_version() {
  std::string* _s = _internal_mutable_protocol_version();
  // @@protoc_insertion_point(field_mutable:nikola.social.ResonantPacket.protocol_version)
  return _s;
}
inline const std::string& ResonantPacket::_internal_protocol_version() const {
  return _impl_.protocol_version_.Get();
}
inline void ResonantPacket::_internal_set_protocol_version(const std::string& value) {
  
  _impl_.protocol_version_.Set(value, GetArenaForAllocation());
}
inline std::string* ResonantPacket::_internal_mutable_protocol_version() {
  
  return _impl_.protocol_version_.Mutable(GetArenaForAllocation());
}
inline std::string* ResonantPacket::release_protocol_version() {
  // @@protoc_insertion_point(field_release:nikola.social.ResonantPacket.protocol_version)
  return _impl_.protocol_version_.Release();
}
inline void ResonantPacket::set_allocated_protocol_version(std::string* protocol_version) {
  if (protocol_version != nullptr) {
    
  } else {
    
  }
  _impl_.protocol_version_.SetAllocated(protocol_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.protocol_version_.IsDefault()) {
    _impl_.protocol_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.ResonantPacket.protocol_version)
}

// -------------------------------------------------------------------

// EmpathySignal

// string session_key = 1;
inline void EmpathySignal::clear_session_key() {
  _impl_.session_key_.ClearToEmpty();
}
inline const std::string& EmpathySignal::session_key() const {
  // @@protoc_insertion_point(field_get:nikola.social.EmpathySignal.session_key)
  return _internal_session_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EmpathySignal::set_session_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.EmpathySignal.session_key)
}
inline std::string* EmpathySignal::mutable_session_key() {
  std::string* _s = _internal_mutable_session_key();
  // @@protoc_insertion_point(field_mutable:nikola.social.EmpathySignal.session_key)
  return _s;
}
inline const std::string& EmpathySignal::_internal_session_key() const {
  return _impl_.session_key_.Get();
}
inline void EmpathySignal::_internal_set_session_key(const std::string& value) {
  
  _impl_.session_key_.Set(value, GetArenaForAllocation());
}
inline std::string* EmpathySignal::_internal_mutable_session_key() {
  
  return _impl_.session_key_.Mutable(GetArenaForAllocation());
}
inline std::string* EmpathySignal::release_session_key() {
  // @@protoc_insertion_point(field_release:nikola.social.EmpathySignal.session_key)
  return _impl_.session_key_.Release();
}
inline void EmpathySignal::set_allocated_session_key(std::string* session_key) {
  if (session_key != nullptr) {
    
  } else {
    
  }
  _impl_.session_key_.SetAllocated(session_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_key_.IsDefault()) {
    _impl_.session_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.EmpathySignal.session_key)
}

// string responding_to_sender = 2;
inline void EmpathySignal::clear_responding_to_sender() {
  _impl_.responding_to_sender_.ClearToEmpty();
}
inline const std::string& EmpathySignal::responding_to_sender() const {
  // @@protoc_insertion_point(field_get:nikola.social.EmpathySignal.responding_to_sender)
  return _internal_responding_to_sender();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EmpathySignal::set_responding_to_sender(ArgT0&& arg0, ArgT... args) {
 
 _impl_.responding_to_sender_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.EmpathySignal.responding_to_sender)
}
inline std::string* EmpathySignal::mutable_responding_to_sender() {
  std::string* _s = _internal_mutable_responding_to_sender();
  // @@protoc_insertion_point(field_mutable:nikola.social.EmpathySignal.responding_to_sender)
  return _s;
}
inline const std::string& EmpathySignal::_internal_responding_to_sender() const {
  return _impl_.responding_to_sender_.Get();
}
inline void EmpathySignal::_internal_set_responding_to_sender(const std::string& value) {
  
  _impl_.responding_to_sender_.Set(value, GetArenaForAllocation());
}
inline std::string* EmpathySignal::_internal_mutable_responding_to_sender() {
  
  return _impl_.responding_to_sender_.Mutable(GetArenaForAllocation());
}
inline std::string* EmpathySignal::release_responding_to_sender() {
  // @@protoc_insertion_point(field_release:nikola.social.EmpathySignal.responding_to_sender)
  return _impl_.responding_to_sender_.Release();
}
inline void EmpathySignal::set_allocated_responding_to_sender(std::string* responding_to_sender) {
  if (responding_to_sender != nullptr) {
    
  } else {
    
  }
  _impl_.responding_to_sender_.SetAllocated(responding_to_sender, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.responding_to_sender_.IsDefault()) {
    _impl_.responding_to_sender_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.EmpathySignal.responding_to_sender)
}

// double resonance_score = 3;
inline void EmpathySignal::clear_resonance_score() {
  _impl_.resonance_score_ = 0;
}
inline double EmpathySignal::_internal_resonance_score() const {
  return _impl_.resonance_score_;
}
inline double EmpathySignal::resonance_score() const {
  // @@protoc_insertion_point(field_get:nikola.social.EmpathySignal.resonance_score)
  return _internal_resonance_score();
}
inline void EmpathySignal::_internal_set_resonance_score(double value) {
  
  _impl_.resonance_score_ = value;
}
inline void EmpathySignal::set_resonance_score(double value) {
  _internal_set_resonance_score(value);
  // @@protoc_insertion_point(field_set:nikola.social.EmpathySignal.resonance_score)
}

// double dissonance_detected = 4;
inline void EmpathySignal::clear_dissonance_detected() {
  _impl_.dissonance_detected_ = 0;
}
inline double EmpathySignal::_internal_dissonance_detected() const {
  return _impl_.dissonance_detected_;
}
inline double EmpathySignal::dissonance_detected() const {
  // @@protoc_insertion_point(field_get:nikola.social.EmpathySignal.dissonance_detected)
  return _internal_dissonance_detected();
}
inline void EmpathySignal::_internal_set_dissonance_detected(double value) {
  
  _impl_.dissonance_detected_ = value;
}
inline void EmpathySignal::set_dissonance_detected(double value) {
  _internal_set_dissonance_detected(value);
  // @@protoc_insertion_point(field_set:nikola.social.EmpathySignal.dissonance_detected)
}

// string feedback_text = 5;
inline void EmpathySignal::clear_feedback_text() {
  _impl_.feedback_text_.ClearToEmpty();
}
inline const std::string& EmpathySignal::feedback_text() const {
  // @@protoc_insertion_point(field_get:nikola.social.EmpathySignal.feedback_text)
  return _internal_feedback_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EmpathySignal::set_feedback_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.feedback_text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.EmpathySignal.feedback_text)
}
inline std::string* EmpathySignal::mutable_feedback_text() {
  std::string* _s = _internal_mutable_feedback_text();
  // @@protoc_insertion_point(field_mutable:nikola.social.EmpathySignal.feedback_text)
  return _s;
}
inline const std::string& EmpathySignal::_internal_feedback_text() const {
  return _impl_.feedback_text_.Get();
}
inline void EmpathySignal::_internal_set_feedback_text(const std::string& value) {
  
  _impl_.feedback_text_.Set(value, GetArenaForAllocation());
}
inline std::string* EmpathySignal::_internal_mutable_feedback_text() {
  
  return _impl_.feedback_text_.Mutable(GetArenaForAllocation());
}
inline std::string* EmpathySignal::release_feedback_text() {
  // @@protoc_insertion_point(field_release:nikola.social.EmpathySignal.feedback_text)
  return _impl_.feedback_text_.Release();
}
inline void EmpathySignal::set_allocated_feedback_text(std::string* feedback_text) {
  if (feedback_text != nullptr) {
    
  } else {
    
  }
  _impl_.feedback_text_.SetAllocated(feedback_text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.feedback_text_.IsDefault()) {
    _impl_.feedback_text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.EmpathySignal.feedback_text)
}

// -------------------------------------------------------------------

// PeerAnnouncement

// string peer_id = 1;
inline void PeerAnnouncement::clear_peer_id() {
  _impl_.peer_id_.ClearToEmpty();
}
inline const std::string& PeerAnnouncement::peer_id() const {
  // @@protoc_insertion_point(field_get:nikola.social.PeerAnnouncement.peer_id)
  return _internal_peer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeerAnnouncement::set_peer_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.peer_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.PeerAnnouncement.peer_id)
}
inline std::string* PeerAnnouncement::mutable_peer_id() {
  std::string* _s = _internal_mutable_peer_id();
  // @@protoc_insertion_point(field_mutable:nikola.social.PeerAnnouncement.peer_id)
  return _s;
}
inline const std::string& PeerAnnouncement::_internal_peer_id() const {
  return _impl_.peer_id_.Get();
}
inline void PeerAnnouncement::_internal_set_peer_id(const std::string& value) {
  
  _impl_.peer_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PeerAnnouncement::_internal_mutable_peer_id() {
  
  return _impl_.peer_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PeerAnnouncement::release_peer_id() {
  // @@protoc_insertion_point(field_release:nikola.social.PeerAnnouncement.peer_id)
  return _impl_.peer_id_.Release();
}
inline void PeerAnnouncement::set_allocated_peer_id(std::string* peer_id) {
  if (peer_id != nullptr) {
    
  } else {
    
  }
  _impl_.peer_id_.SetAllocated(peer_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.peer_id_.IsDefault()) {
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.PeerAnnouncement.peer_id)
}

// string public_key_z85 = 2;
inline void PeerAnnouncement::clear_public_key_z85() {
  _impl_.public_key_z85_.ClearToEmpty();
}
inline const std::string& PeerAnnouncement::public_key_z85() const {
  // @@protoc_insertion_point(field_get:nikola.social.PeerAnnouncement.public_key_z85)
  return _internal_public_key_z85();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeerAnnouncement::set_public_key_z85(ArgT0&& arg0, ArgT... args) {
 
 _impl_.public_key_z85_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.PeerAnnouncement.public_key_z85)
}
inline std::string* PeerAnnouncement::mutable_public_key_z85() {
  std::string* _s = _internal_mutable_public_key_z85();
  // @@protoc_insertion_point(field_mutable:nikola.social.PeerAnnouncement.public_key_z85)
  return _s;
}
inline const std::string& PeerAnnouncement::_internal_public_key_z85() const {
  return _impl_.public_key_z85_.Get();
}
inline void PeerAnnouncement::_internal_set_public_key_z85(const std::string& value) {
  
  _impl_.public_key_z85_.Set(value, GetArenaForAllocation());
}
inline std::string* PeerAnnouncement::_internal_mutable_public_key_z85() {
  
  return _impl_.public_key_z85_.Mutable(GetArenaForAllocation());
}
inline std::string* PeerAnnouncement::release_public_key_z85() {
  // @@protoc_insertion_point(field_release:nikola.social.PeerAnnouncement.public_key_z85)
  return _impl_.public_key_z85_.Release();
}
inline void PeerAnnouncement::set_allocated_public_key_z85(std::string* public_key_z85) {
  if (public_key_z85 != nullptr) {
    
  } else {
    
  }
  _impl_.public_key_z85_.SetAllocated(public_key_z85, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.public_key_z85_.IsDefault()) {
    _impl_.public_key_z85_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.PeerAnnouncement.public_key_z85)
}

// repeated string capabilities = 3;
inline int PeerAnnouncement::_internal_capabilities_size() const {
  return _impl_.capabilities_.size();
}
inline int PeerAnnouncement::capabilities_size() const {
  return _internal_capabilities_size();
}
inline void PeerAnnouncement::clear_capabilities() {
  _impl_.capabilities_.Clear();
}
inline std::string* PeerAnnouncement::add_capabilities() {
  std::string* _s = _internal_add_capabilities();
  // @@protoc_insertion_point(field_add_mutable:nikola.social.PeerAnnouncement.capabilities)
  return _s;
}
inline const std::string& PeerAnnouncement::_internal_capabilities(int index) const {
  return _impl_.capabilities_.Get(index);
}
inline const std::string& PeerAnnouncement::capabilities(int index) const {
  // @@protoc_insertion_point(field_get:nikola.social.PeerAnnouncement.capabilities)
  return _internal_capabilities(index);
}
inline std::string* PeerAnnouncement::mutable_capabilities(int index) {
  // @@protoc_insertion_point(field_mutable:nikola.social.PeerAnnouncement.capabilities)
  return _impl_.capabilities_.Mutable(index);
}
inline void PeerAnnouncement::set_capabilities(int index, const std::string& value) {
  _impl_.capabilities_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:nikola.social.PeerAnnouncement.capabilities)
}
inline void PeerAnnouncement::set_capabilities(int index, std::string&& value) {
  _impl_.capabilities_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:nikola.social.PeerAnnouncement.capabilities)
}
inline void PeerAnnouncement::set_capabilities(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.capabilities_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:nikola.social.PeerAnnouncement.capabilities)
}
inline void PeerAnnouncement::set_capabilities(int index, const char* value, size_t size) {
  _impl_.capabilities_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:nikola.social.PeerAnnouncement.capabilities)
}
inline std::string* PeerAnnouncement::_internal_add_capabilities() {
  return _impl_.capabilities_.Add();
}
inline void PeerAnnouncement::add_capabilities(const std::string& value) {
  _impl_.capabilities_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:nikola.social.PeerAnnouncement.capabilities)
}
inline void PeerAnnouncement::add_capabilities(std::string&& value) {
  _impl_.capabilities_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:nikola.social.PeerAnnouncement.capabilities)
}
inline void PeerAnnouncement::add_capabilities(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.capabilities_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:nikola.social.PeerAnnouncement.capabilities)
}
inline void PeerAnnouncement::add_capabilities(const char* value, size_t size) {
  _impl_.capabilities_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:nikola.social.PeerAnnouncement.capabilities)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
PeerAnnouncement::capabilities() const {
  // @@protoc_insertion_point(field_list:nikola.social.PeerAnnouncement.capabilities)
  return _impl_.capabilities_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
PeerAnnouncement::mutable_capabilities() {
  // @@protoc_insertion_point(field_mutable_list:nikola.social.PeerAnnouncement.capabilities)
  return &_impl_.capabilities_;
}

// string zmq_endpoint = 4;
inline void PeerAnnouncement::clear_zmq_endpoint() {
  _impl_.zmq_endpoint_.ClearToEmpty();
}
inline const std::string& PeerAnnouncement::zmq_endpoint() const {
  // @@protoc_insertion_point(field_get:nikola.social.PeerAnnouncement.zmq_endpoint)
  return _internal_zmq_endpoint();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeerAnnouncement::set_zmq_endpoint(ArgT0&& arg0, ArgT... args) {
 
 _impl_.zmq_endpoint_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nikola.social.PeerAnnouncement.zmq_endpoint)
}
inline std::string* PeerAnnouncement::mutable_zmq_endpoint() {
  std::string* _s = _internal_mutable_zmq_endpoint();
  // @@protoc_insertion_point(field_mutable:nikola.social.PeerAnnouncement.zmq_endpoint)
  return _s;
}
inline const std::string& PeerAnnouncement::_internal_zmq_endpoint() const {
  return _impl_.zmq_endpoint_.Get();
}
inline void PeerAnnouncement::_internal_set_zmq_endpoint(const std::string& value) {
  
  _impl_.zmq_endpoint_.Set(value, GetArenaForAllocation());
}
inline std::string* PeerAnnouncement::_internal_mutable_zmq_endpoint() {
  
  return _impl_.zmq_endpoint_.Mutable(GetArenaForAllocation());
}
inline std::string* PeerAnnouncement::release_zmq_endpoint() {
  // @@protoc_insertion_point(field_release:nikola.social.PeerAnnouncement.zmq_endpoint)
  return _impl_.zmq_endpoint_.Release();
}
inline void PeerAnnouncement::set_allocated_zmq_endpoint(std::string* zmq_endpoint) {
  if (zmq_endpoint != nullptr) {
    
  } else {
    
  }
  _impl_.zmq_endpoint_.SetAllocated(zmq_endpoint, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.zmq_endpoint_.IsDefault()) {
    _impl_.zmq_endpoint_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nikola.social.PeerAnnouncement.zmq_endpoint)
}

// int64 timestamp = 5;
inline void PeerAnnouncement::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t PeerAnnouncement::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t PeerAnnouncement::timestamp() const {
  // @@protoc_insertion_point(field_get:nikola.social.PeerAnnouncement.timestamp)
  return _internal_timestamp();
}
inline void PeerAnnouncement::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void PeerAnnouncement::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:nikola.social.PeerAnnouncement.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace social
}  // namespace nikola

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_irsp_2eproto
