// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irsp.proto

#include "irsp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace nikola {
namespace social {
PROTOBUF_CONSTEXPR ResonantPacket::ResonantPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.emitter_real_)*/{}
  , /*decltype(_impl_.emitter_imag_)*/{}
  , /*decltype(_impl_.intent_vector_)*/{}
  , /*decltype(_impl_.text_payload_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sender_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.session_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.protocol_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ResonantPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResonantPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResonantPacketDefaultTypeInternal() {}
  union {
    ResonantPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResonantPacketDefaultTypeInternal _ResonantPacket_default_instance_;
PROTOBUF_CONSTEXPR EmpathySignal::EmpathySignal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.session_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.responding_to_sender_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.feedback_text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.resonance_score_)*/0
  , /*decltype(_impl_.dissonance_detected_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EmpathySignalDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmpathySignalDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmpathySignalDefaultTypeInternal() {}
  union {
    EmpathySignal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmpathySignalDefaultTypeInternal _EmpathySignal_default_instance_;
PROTOBUF_CONSTEXPR PeerAnnouncement::PeerAnnouncement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.capabilities_)*/{}
  , /*decltype(_impl_.peer_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.public_key_z85_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.zmq_endpoint_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PeerAnnouncementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PeerAnnouncementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PeerAnnouncementDefaultTypeInternal() {}
  union {
    PeerAnnouncement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PeerAnnouncementDefaultTypeInternal _PeerAnnouncement_default_instance_;
}  // namespace social
}  // namespace nikola
static ::_pb::Metadata file_level_metadata_irsp_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_irsp_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_irsp_2eproto = nullptr;

const uint32_t TableStruct_irsp_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.text_payload_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.sender_id_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.session_key_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.emitter_real_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.emitter_imag_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.intent_vector_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::ResonantPacket, _impl_.protocol_version_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nikola::social::EmpathySignal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nikola::social::EmpathySignal, _impl_.session_key_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::EmpathySignal, _impl_.responding_to_sender_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::EmpathySignal, _impl_.resonance_score_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::EmpathySignal, _impl_.dissonance_detected_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::EmpathySignal, _impl_.feedback_text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nikola::social::PeerAnnouncement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nikola::social::PeerAnnouncement, _impl_.peer_id_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::PeerAnnouncement, _impl_.public_key_z85_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::PeerAnnouncement, _impl_.capabilities_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::PeerAnnouncement, _impl_.zmq_endpoint_),
  PROTOBUF_FIELD_OFFSET(::nikola::social::PeerAnnouncement, _impl_.timestamp_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::nikola::social::ResonantPacket)},
  { 14, -1, -1, sizeof(::nikola::social::EmpathySignal)},
  { 25, -1, -1, sizeof(::nikola::social::PeerAnnouncement)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::nikola::social::_ResonantPacket_default_instance_._instance,
  &::nikola::social::_EmpathySignal_default_instance_._instance,
  &::nikola::social::_PeerAnnouncement_default_instance_._instance,
};

const char descriptor_table_protodef_irsp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nirsp.proto\022\rnikola.social\"\276\001\n\016Resonant"
  "Packet\022\024\n\014text_payload\030\001 \001(\t\022\021\n\tsender_i"
  "d\030\002 \001(\t\022\023\n\013session_key\030\003 \001(\t\022\024\n\014emitter_"
  "real\030\004 \003(\001\022\024\n\014emitter_imag\030\005 \003(\001\022\025\n\rinte"
  "nt_vector\030\006 \003(\001\022\021\n\ttimestamp\030\007 \001(\003\022\030\n\020pr"
  "otocol_version\030\010 \001(\t\"\217\001\n\rEmpathySignal\022\023"
  "\n\013session_key\030\001 \001(\t\022\034\n\024responding_to_sen"
  "der\030\002 \001(\t\022\027\n\017resonance_score\030\003 \001(\001\022\033\n\023di"
  "ssonance_detected\030\004 \001(\001\022\025\n\rfeedback_text"
  "\030\005 \001(\t\"z\n\020PeerAnnouncement\022\017\n\007peer_id\030\001 "
  "\001(\t\022\026\n\016public_key_z85\030\002 \001(\t\022\024\n\014capabilit"
  "ies\030\003 \003(\t\022\024\n\014zmq_endpoint\030\004 \001(\t\022\021\n\ttimes"
  "tamp\030\005 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_irsp_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_irsp_2eproto = {
    false, false, 498, descriptor_table_protodef_irsp_2eproto,
    "irsp.proto",
    &descriptor_table_irsp_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_irsp_2eproto::offsets,
    file_level_metadata_irsp_2eproto, file_level_enum_descriptors_irsp_2eproto,
    file_level_service_descriptors_irsp_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_irsp_2eproto_getter() {
  return &descriptor_table_irsp_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_irsp_2eproto(&descriptor_table_irsp_2eproto);
namespace nikola {
namespace social {

// ===================================================================

class ResonantPacket::_Internal {
 public:
};

ResonantPacket::ResonantPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:nikola.social.ResonantPacket)
}
ResonantPacket::ResonantPacket(const ResonantPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ResonantPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.emitter_real_){from._impl_.emitter_real_}
    , decltype(_impl_.emitter_imag_){from._impl_.emitter_imag_}
    , decltype(_impl_.intent_vector_){from._impl_.intent_vector_}
    , decltype(_impl_.text_payload_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.session_key_){}
    , decltype(_impl_.protocol_version_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.text_payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text_payload().empty()) {
    _this->_impl_.text_payload_.Set(from._internal_text_payload(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sender_id().empty()) {
    _this->_impl_.sender_id_.Set(from._internal_sender_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.session_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_key().empty()) {
    _this->_impl_.session_key_.Set(from._internal_session_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.protocol_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.protocol_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_protocol_version().empty()) {
    _this->_impl_.protocol_version_.Set(from._internal_protocol_version(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.timestamp_ = from._impl_.timestamp_;
  // @@protoc_insertion_point(copy_constructor:nikola.social.ResonantPacket)
}

inline void ResonantPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.emitter_real_){arena}
    , decltype(_impl_.emitter_imag_){arena}
    , decltype(_impl_.intent_vector_){arena}
    , decltype(_impl_.text_payload_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.session_key_){}
    , decltype(_impl_.protocol_version_){}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.text_payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.session_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.protocol_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.protocol_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ResonantPacket::~ResonantPacket() {
  // @@protoc_insertion_point(destructor:nikola.social.ResonantPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ResonantPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.emitter_real_.~RepeatedField();
  _impl_.emitter_imag_.~RepeatedField();
  _impl_.intent_vector_.~RepeatedField();
  _impl_.text_payload_.Destroy();
  _impl_.sender_id_.Destroy();
  _impl_.session_key_.Destroy();
  _impl_.protocol_version_.Destroy();
}

void ResonantPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ResonantPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:nikola.social.ResonantPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.emitter_real_.Clear();
  _impl_.emitter_imag_.Clear();
  _impl_.intent_vector_.Clear();
  _impl_.text_payload_.ClearToEmpty();
  _impl_.sender_id_.ClearToEmpty();
  _impl_.session_key_.ClearToEmpty();
  _impl_.protocol_version_.ClearToEmpty();
  _impl_.timestamp_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResonantPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string text_payload = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_text_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.ResonantPacket.text_payload"));
        } else
          goto handle_unusual;
        continue;
      // string sender_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_sender_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.ResonantPacket.sender_id"));
        } else
          goto handle_unusual;
        continue;
      // string session_key = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_session_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.ResonantPacket.session_key"));
        } else
          goto handle_unusual;
        continue;
      // repeated double emitter_real = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_emitter_real(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 33) {
          _internal_add_emitter_real(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double emitter_imag = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_emitter_imag(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 41) {
          _internal_add_emitter_imag(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double intent_vector = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_intent_vector(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 49) {
          _internal_add_intent_vector(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string protocol_version = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_protocol_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.ResonantPacket.protocol_version"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ResonantPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nikola.social.ResonantPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string text_payload = 1;
  if (!this->_internal_text_payload().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text_payload().data(), static_cast<int>(this->_internal_text_payload().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.ResonantPacket.text_payload");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_text_payload(), target);
  }

  // string sender_id = 2;
  if (!this->_internal_sender_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sender_id().data(), static_cast<int>(this->_internal_sender_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.ResonantPacket.sender_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sender_id(), target);
  }

  // string session_key = 3;
  if (!this->_internal_session_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_key().data(), static_cast<int>(this->_internal_session_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.ResonantPacket.session_key");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_session_key(), target);
  }

  // repeated double emitter_real = 4;
  if (this->_internal_emitter_real_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_emitter_real(), target);
  }

  // repeated double emitter_imag = 5;
  if (this->_internal_emitter_imag_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_emitter_imag(), target);
  }

  // repeated double intent_vector = 6;
  if (this->_internal_intent_vector_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_intent_vector(), target);
  }

  // int64 timestamp = 7;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(7, this->_internal_timestamp(), target);
  }

  // string protocol_version = 8;
  if (!this->_internal_protocol_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_protocol_version().data(), static_cast<int>(this->_internal_protocol_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.ResonantPacket.protocol_version");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_protocol_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nikola.social.ResonantPacket)
  return target;
}

size_t ResonantPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nikola.social.ResonantPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double emitter_real = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_emitter_real_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated double emitter_imag = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_emitter_imag_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated double intent_vector = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_intent_vector_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string text_payload = 1;
  if (!this->_internal_text_payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text_payload());
  }

  // string sender_id = 2;
  if (!this->_internal_sender_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sender_id());
  }

  // string session_key = 3;
  if (!this->_internal_session_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_key());
  }

  // string protocol_version = 8;
  if (!this->_internal_protocol_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_protocol_version());
  }

  // int64 timestamp = 7;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResonantPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ResonantPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResonantPacket::GetClassData() const { return &_class_data_; }


void ResonantPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ResonantPacket*>(&to_msg);
  auto& from = static_cast<const ResonantPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nikola.social.ResonantPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.emitter_real_.MergeFrom(from._impl_.emitter_real_);
  _this->_impl_.emitter_imag_.MergeFrom(from._impl_.emitter_imag_);
  _this->_impl_.intent_vector_.MergeFrom(from._impl_.intent_vector_);
  if (!from._internal_text_payload().empty()) {
    _this->_internal_set_text_payload(from._internal_text_payload());
  }
  if (!from._internal_sender_id().empty()) {
    _this->_internal_set_sender_id(from._internal_sender_id());
  }
  if (!from._internal_session_key().empty()) {
    _this->_internal_set_session_key(from._internal_session_key());
  }
  if (!from._internal_protocol_version().empty()) {
    _this->_internal_set_protocol_version(from._internal_protocol_version());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ResonantPacket::CopyFrom(const ResonantPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nikola.social.ResonantPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResonantPacket::IsInitialized() const {
  return true;
}

void ResonantPacket::InternalSwap(ResonantPacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.emitter_real_.InternalSwap(&other->_impl_.emitter_real_);
  _impl_.emitter_imag_.InternalSwap(&other->_impl_.emitter_imag_);
  _impl_.intent_vector_.InternalSwap(&other->_impl_.intent_vector_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_payload_, lhs_arena,
      &other->_impl_.text_payload_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sender_id_, lhs_arena,
      &other->_impl_.sender_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_key_, lhs_arena,
      &other->_impl_.session_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.protocol_version_, lhs_arena,
      &other->_impl_.protocol_version_, rhs_arena
  );
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResonantPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_irsp_2eproto_getter, &descriptor_table_irsp_2eproto_once,
      file_level_metadata_irsp_2eproto[0]);
}

// ===================================================================

class EmpathySignal::_Internal {
 public:
};

EmpathySignal::EmpathySignal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:nikola.social.EmpathySignal)
}
EmpathySignal::EmpathySignal(const EmpathySignal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EmpathySignal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.session_key_){}
    , decltype(_impl_.responding_to_sender_){}
    , decltype(_impl_.feedback_text_){}
    , decltype(_impl_.resonance_score_){}
    , decltype(_impl_.dissonance_detected_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.session_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_key().empty()) {
    _this->_impl_.session_key_.Set(from._internal_session_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.responding_to_sender_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.responding_to_sender_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_responding_to_sender().empty()) {
    _this->_impl_.responding_to_sender_.Set(from._internal_responding_to_sender(), 
      _this->GetArenaForAllocation());
  }
  _impl_.feedback_text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.feedback_text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_feedback_text().empty()) {
    _this->_impl_.feedback_text_.Set(from._internal_feedback_text(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.resonance_score_, &from._impl_.resonance_score_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.dissonance_detected_) -
    reinterpret_cast<char*>(&_impl_.resonance_score_)) + sizeof(_impl_.dissonance_detected_));
  // @@protoc_insertion_point(copy_constructor:nikola.social.EmpathySignal)
}

inline void EmpathySignal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.session_key_){}
    , decltype(_impl_.responding_to_sender_){}
    , decltype(_impl_.feedback_text_){}
    , decltype(_impl_.resonance_score_){0}
    , decltype(_impl_.dissonance_detected_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.session_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.responding_to_sender_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.responding_to_sender_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.feedback_text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.feedback_text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

EmpathySignal::~EmpathySignal() {
  // @@protoc_insertion_point(destructor:nikola.social.EmpathySignal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EmpathySignal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.session_key_.Destroy();
  _impl_.responding_to_sender_.Destroy();
  _impl_.feedback_text_.Destroy();
}

void EmpathySignal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EmpathySignal::Clear() {
// @@protoc_insertion_point(message_clear_start:nikola.social.EmpathySignal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.session_key_.ClearToEmpty();
  _impl_.responding_to_sender_.ClearToEmpty();
  _impl_.feedback_text_.ClearToEmpty();
  ::memset(&_impl_.resonance_score_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.dissonance_detected_) -
      reinterpret_cast<char*>(&_impl_.resonance_score_)) + sizeof(_impl_.dissonance_detected_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EmpathySignal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string session_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_session_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.EmpathySignal.session_key"));
        } else
          goto handle_unusual;
        continue;
      // string responding_to_sender = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_responding_to_sender();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.EmpathySignal.responding_to_sender"));
        } else
          goto handle_unusual;
        continue;
      // double resonance_score = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.resonance_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double dissonance_detected = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.dissonance_detected_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // string feedback_text = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_feedback_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.EmpathySignal.feedback_text"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EmpathySignal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nikola.social.EmpathySignal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string session_key = 1;
  if (!this->_internal_session_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_key().data(), static_cast<int>(this->_internal_session_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.EmpathySignal.session_key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_session_key(), target);
  }

  // string responding_to_sender = 2;
  if (!this->_internal_responding_to_sender().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_responding_to_sender().data(), static_cast<int>(this->_internal_responding_to_sender().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.EmpathySignal.responding_to_sender");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_responding_to_sender(), target);
  }

  // double resonance_score = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_resonance_score = this->_internal_resonance_score();
  uint64_t raw_resonance_score;
  memcpy(&raw_resonance_score, &tmp_resonance_score, sizeof(tmp_resonance_score));
  if (raw_resonance_score != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_resonance_score(), target);
  }

  // double dissonance_detected = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_dissonance_detected = this->_internal_dissonance_detected();
  uint64_t raw_dissonance_detected;
  memcpy(&raw_dissonance_detected, &tmp_dissonance_detected, sizeof(tmp_dissonance_detected));
  if (raw_dissonance_detected != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_dissonance_detected(), target);
  }

  // string feedback_text = 5;
  if (!this->_internal_feedback_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_feedback_text().data(), static_cast<int>(this->_internal_feedback_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.EmpathySignal.feedback_text");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_feedback_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nikola.social.EmpathySignal)
  return target;
}

size_t EmpathySignal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nikola.social.EmpathySignal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string session_key = 1;
  if (!this->_internal_session_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_key());
  }

  // string responding_to_sender = 2;
  if (!this->_internal_responding_to_sender().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_responding_to_sender());
  }

  // string feedback_text = 5;
  if (!this->_internal_feedback_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_feedback_text());
  }

  // double resonance_score = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_resonance_score = this->_internal_resonance_score();
  uint64_t raw_resonance_score;
  memcpy(&raw_resonance_score, &tmp_resonance_score, sizeof(tmp_resonance_score));
  if (raw_resonance_score != 0) {
    total_size += 1 + 8;
  }

  // double dissonance_detected = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_dissonance_detected = this->_internal_dissonance_detected();
  uint64_t raw_dissonance_detected;
  memcpy(&raw_dissonance_detected, &tmp_dissonance_detected, sizeof(tmp_dissonance_detected));
  if (raw_dissonance_detected != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EmpathySignal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EmpathySignal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EmpathySignal::GetClassData() const { return &_class_data_; }


void EmpathySignal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EmpathySignal*>(&to_msg);
  auto& from = static_cast<const EmpathySignal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nikola.social.EmpathySignal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_session_key().empty()) {
    _this->_internal_set_session_key(from._internal_session_key());
  }
  if (!from._internal_responding_to_sender().empty()) {
    _this->_internal_set_responding_to_sender(from._internal_responding_to_sender());
  }
  if (!from._internal_feedback_text().empty()) {
    _this->_internal_set_feedback_text(from._internal_feedback_text());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_resonance_score = from._internal_resonance_score();
  uint64_t raw_resonance_score;
  memcpy(&raw_resonance_score, &tmp_resonance_score, sizeof(tmp_resonance_score));
  if (raw_resonance_score != 0) {
    _this->_internal_set_resonance_score(from._internal_resonance_score());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_dissonance_detected = from._internal_dissonance_detected();
  uint64_t raw_dissonance_detected;
  memcpy(&raw_dissonance_detected, &tmp_dissonance_detected, sizeof(tmp_dissonance_detected));
  if (raw_dissonance_detected != 0) {
    _this->_internal_set_dissonance_detected(from._internal_dissonance_detected());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EmpathySignal::CopyFrom(const EmpathySignal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nikola.social.EmpathySignal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EmpathySignal::IsInitialized() const {
  return true;
}

void EmpathySignal::InternalSwap(EmpathySignal* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_key_, lhs_arena,
      &other->_impl_.session_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.responding_to_sender_, lhs_arena,
      &other->_impl_.responding_to_sender_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.feedback_text_, lhs_arena,
      &other->_impl_.feedback_text_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EmpathySignal, _impl_.dissonance_detected_)
      + sizeof(EmpathySignal::_impl_.dissonance_detected_)
      - PROTOBUF_FIELD_OFFSET(EmpathySignal, _impl_.resonance_score_)>(
          reinterpret_cast<char*>(&_impl_.resonance_score_),
          reinterpret_cast<char*>(&other->_impl_.resonance_score_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EmpathySignal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_irsp_2eproto_getter, &descriptor_table_irsp_2eproto_once,
      file_level_metadata_irsp_2eproto[1]);
}

// ===================================================================

class PeerAnnouncement::_Internal {
 public:
};

PeerAnnouncement::PeerAnnouncement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:nikola.social.PeerAnnouncement)
}
PeerAnnouncement::PeerAnnouncement(const PeerAnnouncement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PeerAnnouncement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.capabilities_){from._impl_.capabilities_}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.public_key_z85_){}
    , decltype(_impl_.zmq_endpoint_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_peer_id().empty()) {
    _this->_impl_.peer_id_.Set(from._internal_peer_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.public_key_z85_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.public_key_z85_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_public_key_z85().empty()) {
    _this->_impl_.public_key_z85_.Set(from._internal_public_key_z85(), 
      _this->GetArenaForAllocation());
  }
  _impl_.zmq_endpoint_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.zmq_endpoint_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_zmq_endpoint().empty()) {
    _this->_impl_.zmq_endpoint_.Set(from._internal_zmq_endpoint(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.timestamp_ = from._impl_.timestamp_;
  // @@protoc_insertion_point(copy_constructor:nikola.social.PeerAnnouncement)
}

inline void PeerAnnouncement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.capabilities_){arena}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.public_key_z85_){}
    , decltype(_impl_.zmq_endpoint_){}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.public_key_z85_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.public_key_z85_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.zmq_endpoint_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.zmq_endpoint_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PeerAnnouncement::~PeerAnnouncement() {
  // @@protoc_insertion_point(destructor:nikola.social.PeerAnnouncement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PeerAnnouncement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.capabilities_.~RepeatedPtrField();
  _impl_.peer_id_.Destroy();
  _impl_.public_key_z85_.Destroy();
  _impl_.zmq_endpoint_.Destroy();
}

void PeerAnnouncement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PeerAnnouncement::Clear() {
// @@protoc_insertion_point(message_clear_start:nikola.social.PeerAnnouncement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.capabilities_.Clear();
  _impl_.peer_id_.ClearToEmpty();
  _impl_.public_key_z85_.ClearToEmpty();
  _impl_.zmq_endpoint_.ClearToEmpty();
  _impl_.timestamp_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PeerAnnouncement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string peer_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_peer_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.PeerAnnouncement.peer_id"));
        } else
          goto handle_unusual;
        continue;
      // string public_key_z85 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_public_key_z85();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.PeerAnnouncement.public_key_z85"));
        } else
          goto handle_unusual;
        continue;
      // repeated string capabilities = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_capabilities();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "nikola.social.PeerAnnouncement.capabilities"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string zmq_endpoint = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_zmq_endpoint();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nikola.social.PeerAnnouncement.zmq_endpoint"));
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PeerAnnouncement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nikola.social.PeerAnnouncement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string peer_id = 1;
  if (!this->_internal_peer_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_peer_id().data(), static_cast<int>(this->_internal_peer_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.PeerAnnouncement.peer_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_peer_id(), target);
  }

  // string public_key_z85 = 2;
  if (!this->_internal_public_key_z85().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_public_key_z85().data(), static_cast<int>(this->_internal_public_key_z85().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.PeerAnnouncement.public_key_z85");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_public_key_z85(), target);
  }

  // repeated string capabilities = 3;
  for (int i = 0, n = this->_internal_capabilities_size(); i < n; i++) {
    const auto& s = this->_internal_capabilities(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.PeerAnnouncement.capabilities");
    target = stream->WriteString(3, s, target);
  }

  // string zmq_endpoint = 4;
  if (!this->_internal_zmq_endpoint().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_zmq_endpoint().data(), static_cast<int>(this->_internal_zmq_endpoint().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nikola.social.PeerAnnouncement.zmq_endpoint");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_zmq_endpoint(), target);
  }

  // int64 timestamp = 5;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nikola.social.PeerAnnouncement)
  return target;
}

size_t PeerAnnouncement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nikola.social.PeerAnnouncement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string capabilities = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.capabilities_.size());
  for (int i = 0, n = _impl_.capabilities_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.capabilities_.Get(i));
  }

  // string peer_id = 1;
  if (!this->_internal_peer_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_peer_id());
  }

  // string public_key_z85 = 2;
  if (!this->_internal_public_key_z85().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_public_key_z85());
  }

  // string zmq_endpoint = 4;
  if (!this->_internal_zmq_endpoint().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_zmq_endpoint());
  }

  // int64 timestamp = 5;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PeerAnnouncement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PeerAnnouncement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PeerAnnouncement::GetClassData() const { return &_class_data_; }


void PeerAnnouncement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PeerAnnouncement*>(&to_msg);
  auto& from = static_cast<const PeerAnnouncement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nikola.social.PeerAnnouncement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.capabilities_.MergeFrom(from._impl_.capabilities_);
  if (!from._internal_peer_id().empty()) {
    _this->_internal_set_peer_id(from._internal_peer_id());
  }
  if (!from._internal_public_key_z85().empty()) {
    _this->_internal_set_public_key_z85(from._internal_public_key_z85());
  }
  if (!from._internal_zmq_endpoint().empty()) {
    _this->_internal_set_zmq_endpoint(from._internal_zmq_endpoint());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PeerAnnouncement::CopyFrom(const PeerAnnouncement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nikola.social.PeerAnnouncement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PeerAnnouncement::IsInitialized() const {
  return true;
}

void PeerAnnouncement::InternalSwap(PeerAnnouncement* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.capabilities_.InternalSwap(&other->_impl_.capabilities_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.peer_id_, lhs_arena,
      &other->_impl_.peer_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.public_key_z85_, lhs_arena,
      &other->_impl_.public_key_z85_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.zmq_endpoint_, lhs_arena,
      &other->_impl_.zmq_endpoint_, rhs_arena
  );
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PeerAnnouncement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_irsp_2eproto_getter, &descriptor_table_irsp_2eproto_once,
      file_level_metadata_irsp_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace social
}  // namespace nikola
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::nikola::social::ResonantPacket*
Arena::CreateMaybeMessage< ::nikola::social::ResonantPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nikola::social::ResonantPacket >(arena);
}
template<> PROTOBUF_NOINLINE ::nikola::social::EmpathySignal*
Arena::CreateMaybeMessage< ::nikola::social::EmpathySignal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nikola::social::EmpathySignal >(arena);
}
template<> PROTOBUF_NOINLINE ::nikola::social::PeerAnnouncement*
Arena::CreateMaybeMessage< ::nikola::social::PeerAnnouncement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nikola::social::PeerAnnouncement >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
